In [1]:
import os
import sys

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sb

%matplotlib inline

In [2]:
os.getcwd()

'/home/anthony/summer-bursary-2018/Bacteria'

In [3]:
os.listdir()

['.ipynb_checkpoints', 'data', 'Untitled.ipynb']

In [4]:
os.listdir('data')

['Classific.py',
 'graphs.pdf',
 '16ms_32ms_growth_phase_spectra.csv',
 'PC6allwavelengths.png',
 '16_ms_lag_codes.csv']

In [5]:
df = pd.read_csv('data/16ms_32ms_growth_phase_spectra.csv')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1043 entries, 0 to 1042
Columns: 271 entries, wavelength to sa08_32ms_stat
dtypes: float64(271)
memory usage: 2.2 MB

In [7]:
df.describe()

,wavelength,bc01_16ms_lag,bc02_16ms_lag,bc03_16ms_lag,bc04_16ms_lag,bc05_16ms_lag,bc06_16ms_lag,bc07_16ms_lag,bc08_16ms_lag,bc09_16ms_lag,...,sa07_16ms_stat,sa08_16ms_stat,sa01_32ms_stat,sa02_32ms_stat,sa03_32ms_stat,sa04_32ms_stat,sa05_32ms_stat,sa06_32ms_stat,sa07_32ms_stat,sa08_32ms_stat
count,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,...,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000
mean,594.306442,340.917966,218.282554,410.265450,402.411758,147.930946,304.443366,690.243351,615.625463,508.217097,...,1617.105057,1424.455291,1678.851611,1582.324367,1752.327722,1072.604400,2487.669405,1599.289495,1902.815892,1755.026657
std,112.580390,517.453981,328.263253,632.792734,584.358827,213.381498,457.365956,1076.320701,1006.404767,829.675942,...,2683.151537,2381.357464,2879.515933,2702.094106,2988.042428,1838.334717,4268.994423,2653.006792,3166.968570,2929.745473
min,395.494100,-3.510400,-2.800760,-2.581292,-2.554170,-2.985820,-3.429370,-2.280780,-4.327390,-3.340390,...,-2.563420,-1.462970,-2.103330,-1.784151,-2.269830,-1.515490,-0.659870,-11.208600,-1.796640,-0.447010
25%,497.482200,3.738191,2.116139,3.614560,4.258268,3.017208,3.429759,4.382186,3.291279,3.093110,...,12.687795,10.883005,9.192903,7.764677,8.325252,6.301859,13.161080,11.004515,11.811570,10.710685
50%,596.374400,40.780240,27.023980,48.616896,58.972290,24.396270,37.316280,78.138510,46.407810,41.594080,...,130.242300,104.561900,108.065100,101.703279,111.690200,67.091590,156.489900,129.346400,145.233800,130.134800
75%,692.170600,496.754350,319.173550,571.801010,629.260350,223.730650,446.739200,940.880800,775.154550,630.964700,...,1936.329500,1679.898000,1858.899000,1765.909212,1966.221500,1192.396500,2769.300000,1908.102500,2265.020500,2097.588000
max,784.870900,1649.755000,1044.867000,2050.509445,1755.384000,670.982500,1426.308000,3542.053000,3369.752000,2848.575000,...,9235.687000,8223.580000,9870.242000,9234.608023,10242.690000,6358.552000,14776.430000,9130.342000,10880.640000,10086.280000

In [8]:
df.isnull().values.any()

False

In [14]:
df_32ms = pd.concat([df['wavelength'], df.filter(regex='32ms')], axis=1)
df_32ms.columns = df_32ms.columns.str.replace("_32ms", "")
df_32ms.describe()

,wavelength,bc01_lag,bc02_lag,bc03_lag,bc04_lag,bc05_lag,bc06_lag,bc07_lag,bc08_lag,bc09_lag,...,sa07_log,sa08_log,sa01_stat,sa02_stat,sa03_stat,sa04_stat,sa05_stat,sa06_stat,sa07_stat,sa08_stat
count,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,...,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000
mean,594.306442,463.254155,316.392618,552.623759,465.022246,175.743983,413.784704,844.072374,851.591885,646.697807,...,2867.141815,2696.802118,1678.851611,1582.324367,1752.327722,1072.604400,2487.669405,1599.289495,1902.815892,1755.026657
std,112.580390,699.283252,476.657170,854.591596,685.749253,258.675914,621.866857,1331.090054,1392.304143,1067.856167,...,4730.333102,4476.002942,2879.515933,2702.094106,2988.042428,1838.334717,4268.994423,2653.006792,3166.968570,2929.745473
min,395.494100,-2.730370,-2.282100,-2.022019,-1.540730,-1.990560,-1.673860,-1.000280,-1.259630,-1.690850,...,-1.139850,-1.882630,-2.103330,-1.784151,-2.269830,-1.515490,-0.659870,-11.208600,-1.796640,-0.447010
25%,497.482200,4.421786,3.921701,5.100123,4.968519,2.882823,4.043047,5.603591,4.673628,2.309737,...,14.042395,14.299990,9.192903,7.764677,8.325252,6.301859,13.161080,11.004515,11.811570,10.710685
50%,596.374400,60.336290,42.483700,62.138347,63.970220,25.816110,50.922750,84.657250,64.188980,43.552670,...,205.682800,193.290100,108.065100,101.703279,111.690200,67.091590,156.489900,129.346400,145.233800,130.134800
75%,692.170600,671.629550,460.699250,761.548722,717.397750,264.806850,612.134250,1131.572500,1075.584000,800.763400,...,3560.614000,3266.976500,1858.899000,1765.909212,1966.221500,1192.396500,2769.300000,1908.102500,2265.020500,2097.588000
max,784.870900,2172.793000,1514.490000,2750.493031,2088.023000,815.180300,1930.534000,4408.011000,4658.405000,3643.471000,...,15771.490000,15108.770000,9870.242000,9234.608023,10242.690000,6358.552000,14776.430000,9130.342000,10880.640000,10086.280000

In [18]:
print(df_32ms.columns.values)

['wavelength' 'bc01_lag' 'bc02_lag' 'bc03_lag' 'bc04_lag' 'bc05_lag'
 'bc06_lag' 'bc07_lag' 'bc08_lag' 'bc09_lag' 'bc10_lag' 'bc11_lag'
 'bc12_lag' 'bc01_log' 'bc02_log' 'bc03_log' 'bc04_log' 'bc05_log'
 'bc06_log' 'bc07_log' 'bc08_log' 'bc09_log' 'bc10_log' 'bc11_log'
 'bc12_log' 'bc01_stat' 'bc02_stat' 'bc03_stat' 'bc04_stat' 'bc05_stat'
 'bc06_stat' 'bc07_stat' 'bc08_stat' 'bc09_stat' 'bc10_stat' 'bc11_stat'
 'bc12_stat' 'ec01_lag' 'ec02_lag' 'ec03_lag' 'ec04_lag' 'ec05_lag'
 'ec06_lag' 'ec07_lag' 'ec08_lag' 'ec01_log' 'ec02_log' 'ec03_log'
 'ec04_log' 'ec05_log' 'ec01_stat' 'ec02_stat' 'ec03_stat' 'ec04_stat'
 'ec05_stat' 'ec06_stat' 'ec07_stat' 'ec08_stat' 'ec09_stat' 'lm01_lag'
 'lm02_lag' 'lm03_lag' 'lm04_lag' 'lm05_lag' 'lm01_log' 'lm02_log'
 'lm03_log' 'lm01_stat' 'lm02_stat' 'lm03_stat' 'pa01_lag' 'pa02_lag'
 'pa03_lag' 'pa04_lag' 'pa05_lag' 'pa06_lag' 'pa01_log' 'pa02_log'
 'pa03_log' 'pa04_log' 'pa05_log' 'pa06_log' 'pa07_log' 'pa08_log'
 'pa01_stat' 'pa02_stat' 'pa03_stat' 'pa04_stat' 'pa05_stat' 'pa06_stat'
 'pa07_stat' 'pa08_stat' 'se01_lag' 'se02_lag' 'se03_lag' 'se04_lag'
 'se05_lag' 'se01_log' 'se02_log' 'se03_log' 'se04_log' 'se05_log'
 'se01_stat' 'se02_stat' 'se03_stat' 'se04_stat' 'se05_stat' 'se06_stat'
 'se07_stat' 'sa01_lag' 'sa02_lag' 'sa03_lag' 'sa04_lag' 'sa05_lag'
 'sa06_lag' 'sa07_lag' 'sa08_lag' 'sa09_lag' 'sa10_lag' 'sa11_lag'
 'sa01_log' 'sa02_log' 'sa03_log' 'sa04_log' 'sa05_log' 'sa06_log'
 'sa07_log' 'sa08_log' 'sa01_stat' 'sa02_stat' 'sa03_stat' 'sa04_stat'
 'sa05_stat' 'sa06_stat' 'sa07_stat' 'sa08_stat']

In [43]:
growth_stages = ['lag', 'log', 'stat']

In [26]:
bacteria_prefixes = np.unique(list(map(lambda col_name: col_name[:2], df_32ms.columns.values[1:])))
bacteria_prefixes

array(['bc', 'ec', 'lm', 'pa', 'sa', 'se'], dtype='<U2')

In [20]:
df_log = pd.concat([df_32ms['wavelength'], df_32ms.filter(regex='log')], axis=1)
df_log.columns = df_log.columns.str.replace("_log", "")
df_log.describe()

,wavelength,bc01,bc02,bc03,bc04,bc05,bc06,bc07,bc08,bc09,...,se04,se05,sa01,sa02,sa03,sa04,sa05,sa06,sa07,sa08
count,1043.000000,1043.00000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,...,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000,1043.000000
mean,594.306442,2502.80724,3385.178316,2946.745040,2798.810520,2195.309117,2416.455533,3841.031967,2738.136345,3369.985470,...,647.002590,769.750561,3497.164747,3235.423892,2193.388301,2138.616955,2364.282840,2540.915732,2867.141815,2696.802118
std,112.580390,4293.12649,5667.549982,4974.315522,4591.327001,3589.149056,4102.201836,6538.616705,4711.052038,5796.362787,...,1070.991666,1254.468790,5899.465758,5360.922997,3709.857102,3610.480020,3996.344241,4258.718654,4730.333102,4476.002942
min,395.494100,-1.58969,-1.824730,-0.497792,-1.112102,-0.937290,-1.227480,-0.870660,-1.080560,-0.914640,...,-1.978870,-1.615040,-1.042910,-1.942417,-1.200680,-11.583800,-0.880800,-7.433820,-1.139850,-1.882630
25%,497.482200,10.99024,15.176830,12.471825,13.706294,12.371920,9.669530,14.681090,9.488705,12.477145,...,4.475031,7.956585,14.940325,16.161212,10.380990,8.249139,12.250020,13.318970,14.042395,14.299990
50%,596.374400,150.55700,226.717400,184.804933,205.720020,171.853200,144.595500,216.208400,145.779500,175.966400,...,54.896460,77.365310,217.293000,218.590943,139.719100,134.958500,151.135600,175.775100,205.682800,193.290100
75%,692.170600,2775.53350,4010.520500,3432.008015,3482.539389,2751.229500,2787.952500,4385.676500,3041.568500,3764.482500,...,777.062100,939.321150,4076.114500,3925.815750,2533.674000,2492.529500,2711.600000,2976.865000,3560.614000,3266.976500
max,784.870900,14774.96000,19032.170000,16776.817370,15150.681080,11962.750000,14034.680000,20744.120000,16293.300000,19925.430000,...,3707.514000,4364.978000,19787.950000,17621.332460,12601.840000,12390.860000,13594.050000,14492.750000,15771.490000,15108.770000

In [41]:
species_dfs = []

for species in bacteria_prefixes:
    species_df = df_log.filter(regex=species)
    species_df.columns = species_df.columns.str.replace(species, "")
    species_df.columns = pd.MultiIndex.from_product([[species], species_df.columns])
    
    species_dfs.append(species_df)
    
df_log_multilevel = pd.concat(species_dfs, axis=1)
df_log_multilevel.head()

         bc                                                              \
         01        02        03        04        05        06        07
0 -0.841600  0.933573  1.040834  0.397172  0.040751  0.131516  0.538978
1  0.233775 -1.018440 -0.181014  0.357456  0.814995  0.920616 -0.538970
2  0.327287  0.594086  0.678805  0.158870 -0.163000 -0.131520 -0.870660
3  2.524927  2.121874  0.316797  3.137825 -0.937290  1.008343  0.787798
4  1.215715  1.485336  3.077486  1.946271 -0.611280  0.306892  2.529204

                                   ...           sa                      \
         08        09        10    ...           04        05        06
0  0.040020  0.914642 -2.167560    ...    -0.501820 -0.671090 -0.435810
1  0.040020 -0.083150  0.572499    ...     4.432210  0.419424  2.396509
2 -0.920470  0.582044 -3.475970    ...    -5.310690 -0.880800  1.830258
3  1.480855  2.910399  4.061280    ...     1.258679  1.551982  3.278458
4  0.680393  2.577809 -0.820570    ...    -1.384450  0.419451  5.728001

                                 se
         07            08        01        02        03        04        05
0 -0.591040  1.090000e-07 -0.517480  0.044413  0.084227  0.430159  0.807457
1 -1.139850 -1.313400e-01  0.776206  0.355303  0.084226 -0.817290  0.403729
2 -0.295520 -1.006970e+00  0.646838 -0.710610 -0.252683  0.645221 -0.242240
3  1.604329  2.057846e+00  0.690001 -1.065970 -0.168460 -0.129050 -0.726750
4  0.633299  3.853026e+00  0.301877  1.154813  0.168463 -0.731300 -0.403760

[5 rows x 41 columns]

In [55]:
pd.MultiIndex.from_product([['lag']] + df_log_multilevel.columns.levels)

MultiIndex(levels=[['lag'], ['bc', 'ec', 'lm', 'pa', 'sa', 'se'], ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']],
           labels=[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]])

In [78]:
growth_stage_dfs = []

for growth_stage in growth_stages:
    growth_stage_df = df_32ms.filter(regex=growth_stage)
    
    species_dfs = []

    for species in bacteria_prefixes:
        species_df = growth_stage_df.filter(regex=species)
        species_df.columns = species_df.columns.str.replace(species, "")
        species_df.columns = species_df.columns.str.replace("_%s" % growth_stage, "")
        species_df.columns = pd.MultiIndex.from_product([[species], species_df.columns])

        species_dfs.append(species_df)

    species_multilevel_df = pd.concat(species_dfs, axis=1)
        
    growth_stage_dfs.append(species_multilevel_df)
    
growth_stages_df = pd.concat(growth_stage_dfs, axis=1, keys=growth_stages)
growth_stages_df.head()

        lag                                                              \
         bc
         01        02        03        04        05        06        07
0 -0.086670 -0.456390  0.516225 -1.540620  0.456133 -1.183870  0.800218
1  0.996705 -0.165960 -0.043018 -1.054100  0.663466  0.612345  0.040013
2  0.650022 -0.746820 -0.731316 -0.648680  0.995199 -0.204110 -0.440120
3 -0.346710  0.622385  0.817394 -0.202730  1.327006  0.285776  1.000333
4  1.993549  1.078807 -0.860428  0.243273  0.248810  0.449092  1.000333

                                   ...         stat                      \
                                   ...           sa
         08        09        10    ...           06        07        08
0  0.487562  0.494845  3.310051    ...     1.046171 -0.219080 -0.000002
1  0.162518  0.329893  1.829989    ...    -2.803270 -0.744870  0.893972
2 -1.097000  0.288661  0.973460    ...     0.000002 -0.394340  1.178423
3  0.203161  0.329910 -2.733980    ...     6.001085  2.059493  1.341045
4 -1.097080  0.659837  4.844247    ...    -2.476320  0.438183  0.934681


         se
         01        02        03        04        05        06        07
0  0.655876 -1.283520 -0.578877 -0.489380 -0.394080 -0.731570  0.080716
1 -1.093120 -0.385060 -0.222642  0.448589  0.157629  0.559429  0.121073
2 -0.349810 -0.385060  0.133583  0.163123 -1.930980 -0.516400 -0.847510
3 -0.087450 -1.069670  0.311717  0.122343  1.418768  0.086071  0.403608
4  1.005742  1.839845  0.534377 -0.203920 -0.472910  0.903758 -0.201800

[5 rows x 135 columns]

In [79]:
growth_stages_df.describe()

               lag                                                      \
                bc
                01           02           03           04           05
count  1043.000000  1043.000000  1043.000000  1043.000000  1043.000000
mean    463.254155   316.392618   552.623759   465.022246   175.743983
std     699.283252   476.657170   854.591596   685.749253   258.675914
min      -2.730370    -2.282100    -2.022019    -1.540730    -1.990560
25%       4.421786     3.921701     5.100123     4.968519     2.882823
50%      60.336290    42.483700    62.138347    63.970220    25.816110
75%     671.629550   460.699250   761.548722   717.397750   264.806850
max    2172.793000  1514.490000  2750.493031  2088.023000   815.180300

                                                                        \

                06           07           08           09           10
count  1043.000000  1043.000000  1043.000000  1043.000000  1043.000000
mean    413.784704   844.072374   851.591885   646.697807   366.611195
std     621.866857  1331.090054  1392.304143  1067.856167   554.603005
min      -1.673860    -1.000280    -1.259630    -1.690850   -11.798100
25%       4.043047     5.603591     4.673628     2.309737     2.812726
50%      50.922750    84.657250    64.188980    43.552670    41.949670
75%     612.134250  1131.572500  1075.584000   800.763400   543.530450
max    1930.534000  4408.011000  4658.405000  3643.471000  1765.544000

          ...              stat                                           \
          ...                sa                                       se
          ...                06            07            08           01
count     ...       1043.000000   1043.000000   1043.000000  1043.000000
mean      ...       1599.289495   1902.815892   1755.026657   446.366505
std       ...       2653.006792   3166.968570   2929.745473   705.206690
min       ...        -11.208600     -1.796640     -0.447010    -2.404990
25%       ...         11.004515     11.811570     10.710685     4.176833
50%       ...        129.346400    145.233800    130.134800    48.709410
75%       ...       1908.102500   2265.020500   2097.588000   593.165750
max       ...       9130.342000  10880.640000  10086.280000  2307.586000

                                                                        \

                02           03           04           05           06
count  1043.000000  1043.000000  1043.000000  1043.000000  1043.000000
mean    590.585346   419.127158   793.937742  1199.566248   810.087409
std     999.239678   713.758593  1383.551956  2065.302325  1402.507435
min      -1.283620    -2.003949    -1.182740    -1.930980    -3.227710
25%       3.209773     2.093012     7.383646     5.480067     3.099317
50%      37.814460    24.332918    55.684650    68.544360    46.416650
75%     676.059400   474.192789   817.292200  1327.228000   881.807350
max    3394.480000  2433.270406  4896.256000  7163.583000  4885.154000



                07
count  1043.000000
mean   1064.991517
std    1843.400931
min      -1.210800
25%       5.106932
50%      59.201140
75%    1163.798500
max    6421.733000

[8 rows x 135 columns]

In [81]:
growth_stages_df.to_csv('data/growth_stages.csv')
df_32ms['wavelength'].to_csv('data/wavelengths.csv')